### ISSUE TITLE
请问这个GIF怎么录制的啊？

### ISSUE THREAD

**Issue by xhzengAIB** [KittenYang/KYJellyPullToRefresh#2]
@KittenYang 
你好！

怎么把gif录制成带立体效果的呢？ 

Jack

**Comment by KittenYang** [comment]
我比较讲究，这个是用AE做的，虽然有点傻但是为了最终效果还是想认真一下，承让了。

**Comment by xhzengAIB** [comment]
你过于谦虚了，其实我也想学习一下怎么制作，我也需要和你一样认真一下，能发个制作教程吗？

**Comment by KittenYang** [comment]
我是看http://i.youku.com/u/UMTA4MDM1NDc2 这个学的，希望能帮到你。

**Comment by KittenYang** [comment]
another: http://i.youku.com/u/UOTgwMDM3ODg=

**Comment by xhzengAIB** [comment]
打不开链接哦！

**Comment by xhzengAIB** [comment]
我推测一下：
是不是用其他工具录制模拟器的屏幕，生成一个gif，然后把这个gif放在AE里面做一个角度变换，然后生成另外一个gif，这样就可以做到一个3D的gif了，是这样吗？

因为我打不开那优酷的链接，所以还不知道怎么入手，谢谢你的解答。

Jack

**Comment by KittenYang** [comment]
我一般是这样的：用QuickTime Player录制iPhone屏幕，生成一个视频；准备一个App展示的mockup (谷歌上有很多)；把视频和mockup一起拖入AE;使用 "滤镜" 里面的 ”边角定位(Corner Pin)" 把视频的四角钉在Mockup四角上；Export为视频；接下来视频转gif方法就很多了：PS、或者[GIFBrewery](https://itunes.apple.com/us/app/gif-brewery/id435989461?mt=12)

**Comment by xhzengAIB** [comment]
谢谢你热心的回答！
